language: node_js
env:
  global:
  - GH_USER: nelson
node_js:
- '6.0'
install:
- yarn add gulp bower -g 
- yarn
- bower install
- gulp build
- mkdir out
- cp -r dist/* out
- cd out
- git init
- git config user.name nelson119
- git config user.email nelson119@outlook.com
- git remote add origin $GH_REF
- git add .
- git commit -m "Deployed to Github Pages"
- git push -f --quiet origin master:gh-pages
- cd ..
